language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install: "pip install -r test_requirements.txt"
script: python pimpmybot/testing.py
after_success:
  - coverage run pimpmybot/testing.py
  - coveralls